### ISSUE TITLE
ping range

### ISSUE THREAD

**Issue by jungle-boogie** [mehrdadrad/mylg#69] opened 2016-12-09 20:01 UTC
Hi All,

when pinging `192.168.0.0/24`, a result is duplicated:

```
% sudo /usr/bin/time mylg ping 192.168.0.0/24 | ack alive
Password:
192.168.0.1 is alive (1.3574 ms)
192.168.0.3 is alive (0.4098 ms)
192.168.0.4 is alive (10.5379 ms)
192.168.0.5 is alive (2.4246 ms)
192.168.0.6 is alive (0.3861 ms)
192.168.0.7 is alive (83.5629 ms)
192.168.0.8 is alive (14.9203 ms)
192.168.0.11 is alive (4.3422 ms)
192.168.0.12 is alive (9.0886 ms)
192.168.0.13 is alive (0.2380 ms)
192.168.0.15 is alive (0.0939 ms)
192.168.0.17 is alive (0.4137 ms)
192.168.0.20 is alive (12.5586 ms)
192.168.0.22 is alive (0.4163 ms)
192.168.0.26 is alive (0.4149 ms)
192.168.0.100 is alive (0.9317 ms)
192.168.0.137 is alive (0.6224 ms)
192.168.0.140 is alive (0.4299 ms)
192.168.0.15 is alive (0.0967 ms)
      477.88 real         0.71 user         0.05 sys
```

Notice `192.168.0.15` in listed twice. 192.168.0.15 is the machine I'm running `mylg` from.

**Comment by mehrdadrad** [comment] 2016-12-10 07:24
good catch 👍  I just committed a fix pls try again and let me know. Thanks!

**Comment by jungle-boogie** [comment] 2016-12-11 04:29
much better but what's up with this?
`192.168.0.100 is alive (1481429370444.3538 ms)`

Is that a sum of scanning the full /24 range?

**Comment by mehrdadrad** [comment] 2016-12-11 04:33
did you try w/ the last commit? I did another commit today

**Comment by jungle-boogie** [comment] 2016-12-11 05:11
Yes, this is with the latest update.

**Comment by mehrdadrad** [comment] 2016-12-11 08:02
when you get a chance try again w/ latest code. I checked w/ diff scenarios and it passed!

**Comment by jungle-boogie** [comment] 2016-12-11 17:44
This still repeats results in the scan.

```
192.168.0.1 is alive (2.6196 ms)
192.168.0.2 is alive (81.7707 ms)
192.168.0.3 is alive (0.3931 ms)
192.168.0.4 is alive (5.8295 ms)
192.168.0.5 is alive (4.5503 ms)
192.168.0.6 is alive (0.3875 ms)
192.168.0.8 is alive (8.6852 ms)
192.168.0.11 is alive (1.9782 ms)
192.168.0.12 is alive (10.4139 ms)
192.168.0.13 is alive (0.2777 ms)
192.168.0.15 is alive (0.0939 ms)
192.168.0.17 is alive (0.2249 ms)
192.168.0.20 is alive (0.2361 ms)
192.168.0.22 is alive (0.4109 ms)
192.168.0.26 is alive (0.4188 ms)
192.168.0.100 is alive (0.4068 ms)
192.168.0.137 is alive (0.6168 ms)
192.168.0.140 is alive (0.4065 ms)
192.168.0.15 is alive (0.0908 ms)
```

Notice this has 192.168.0.15 twice. This has the latest code from github.

**Comment by mehrdadrad** [comment] 2016-12-21 07:41
I couldn't duplicate this issue. I remember you had same issue w/ scan

**Comment by jungle-boogie** [comment] 2016-12-21 18:38
> I couldn't duplicate this issue. I remember you had same issue w/ scan

yes, that's right and you fixed it with the code.

**Comment by mehrdadrad** [comment] 2016-12-21 18:41
Correct, I added unique function to stop showing duplicate!

**Comment by mehrdadrad** [comment] 2016-12-21 18:53
@gummiboll when you get a chance can you test it pls

**Comment by gummiboll** [comment] 2016-12-21 22:04
I can duplicate this with a fresh build of mylg:

```
untzuntz:mylg emil$ sudo ./bin/mylg ping 10.0.1.0/24|grep alive
10.0.1.1 is alive (2.395 ms)
10.0.1.1 is alive (1.144 ms)
10.0.1.2 is alive (2.594 ms)
10.0.1.8 is alive (0.134 ms)
10.0.1.10 is alive (3.357 ms)
10.0.1.8 is alive (0.102 ms)
```

.1 is my gw and .8 is the laptop I'm pinging from if that helps

**Comment by mehrdadrad** [comment] 2016-12-21 22:13
@gummiboll Thanks! that's help

**Comment by mehrdadrad** [comment] 2016-12-22 03:38
@gummiboll I think the 10.0.1.1 shouldn't be showed up per last change but still no idea why 10.0.1.8 duplicated.

**Comment by mehrdadrad** [comment] 2016-12-22 06:00
I think I found the issue for the 10.0.1.8 issue. the root cause is broadcast ip address. it should be skipped through the ping loop :-)

**Comment by mehrdadrad** [comment] 2016-12-22 07:05
@jungle-boogie @gummiboll it fixed pls try again when you get a chance

**Comment by gummiboll** [comment] 2016-12-22 08:24
You did it @mehrdadrad, good job!

```
untzuntz:mylg emil$ sudo ./mylg ping 10.0.1.0/24|grep alive
10.0.1.1 is alive (16.469 ms)
10.0.1.2 is alive (2.823 ms)
10.0.1.8 is alive (0.168 ms)
10.0.1.10 is alive (3.602 ms)
```

**Comment by mehrdadrad** [comment] 2016-12-22 13:25
@gummiboll Thanks Emil!

**Closed by mehrdadrad** 2016-12-22 13:25 UTC
Labels: bug
