### ISSUE TITLE
hping with ipv6

### ISSUE THREAD

**Issue by jungle-boogie** [mehrdadrad/mylg#54] opened 2016-11-29 17:20 UTC
Hi,

From looking at the `hping` options, it doesn't seem there's an option to connect via ipv6:

```
    usage:
          hping url [options]

    options:
          -c   count        Send 'count' requests (default: 5)
          -t   timeout      Set a time limit for requests in ms/s (default: 2s)
          -i   interval     Set a wait time between sending each request in ms/s (default: 1s)
          -m   method       HTTP methods: GET/POST/HEAD (default: head)
          -d   data         Sending the given data (text/json) (default: "mylg")
          -u   user agent   Set user agent
          -q                Quiet reqular output
          -k                Enable keep alive
          -dc               Disable compression
          -nc               Don_t check the server certificate
          -trace            Provides the events within client requests
          -json             Export statistics as json format

    Proxy:
        hping parses environment variables HTTP(S)_PROXY to determine which/if any
        proxies should be used.
```

**Comment by gummiboll** [comment] 2016-11-29 18:54
I've been tinkering with this since I believe the ability to force hping to use IPv4/IPv6 would be a great addition to it.

The problem is that golangs http client can't (at least from my investigation)  be forced to use IPv4/IPv6 easily. From my understanding there are two ways to solve this:

- Do some magic with Dial and force which IP-version that should be used. It doesn't seem to be very straight forward tho.

- Leverage the fact that before the actual requests are sent, [mylg resolves](https://github.com/mehrdadrad/mylg/blob/master/http/ping/ping.go#L123) the hostname. I'm thinking a setup like this: hping resolves the address with the specified IP-version (if no version is specified; use the default happy eyeballs setup) and then when the requests are sent, send them against the IP-address instead but specify a Host-header with the hostname so that the receiving webbserver knows which site is requested.

I'm leaning towards the second setup but it feels a bit.. icky. What are your thoughts on this, @mehrdadrad? Do you know of a better way to solve this or have I misunderstood something about golangs http client and its easy to specify the IP-version?

**Comment by jungle-boogie** [comment] 2016-11-29 19:55
I checked on the #go-nuts IRC channel. Perhaps this is clear to you two:

So net.Dial gives you a net.Conn, you put the net.Conn in the http.Transport, you put the http.Transport in the http.Client

**Comment by mehrdadrad** [comment] 2016-11-29 19:59
@gummiboll 
I didn't try it yet but may it works once we resolved to specific IP address
```
    http.DefaultTransport.(*http.Transport).DialContext = func(ctx context.Context, network, addr string) (net.Conn, error) {
               addr = net.JoinHostPort(ipAddress, port)
               return dialer.DialContext(ctx, network, addr)
    }
```

**Comment by mehrdadrad** [comment] 2016-11-29 22:51
another suggestion from Golang slack channel
```
t := &http.Transport{
		DialContext: func(ctx context.Context, network, addr string) (net.Conn, error) {
			if conn, err := net.Dial("tcp6", addr); err == nil {
				return conn, nil
			}

			return net.Dial("tcp", addr)
		},
	}

	c := &http.Client{
		Transport: t,
	}
```

**Comment by gummiboll** [comment] 2016-11-30 08:27
That seems quite clean. Will fiddle a little with it and make a PR. :)

**Comment by gummiboll** [comment] 2016-12-01 17:46
PR submitted.

However, note the issue mentioned in it about happy eyeballs. I.e; since mylg first resolves the ip-address of the hostname and then again when it does the actual requests it can cause a issue where you think its pinging the IPv4-address but instead it pings the IPv6-address or the other way around. From testing this it seems like ```ResolveIPAddr``` prefers IPv4 over IPv6 but I haven't read through the sorce for ```ResolveIPAddr``` so I can be wrong.

As I see it, there is a couple of ways to handle this:

- Force IPv4 if -6 isnt specified
- After resolving the ip-address, work out if its IPv4 or IPv6 and then make sure the requests are sent with the same ip version. - If I'm correct about ```ResolveIPAddr```prefering IPv4 this is essentially the same as forcing IPv4.
- After resolving the ip-address, send the requests to the ip-address instead and specify a Host-header with the correct hostname.
- Just ignore this issue.

**Comment by mehrdadrad** [comment] 2016-12-01 19:07
@gummiboll 
How about this:
```
+ 316         DialContext: func(ctx context.Context, network, addr string) (net.Conn, error) {
+ 317             if r := strings.Index(p.rAddr.String(), ":"); r != -1 {
+ 318                 return net.Dial("tcp6", addr)
+ 319             }
+ 320             return net.Dial("tcp4", addr)
+ 321         },

```

**Comment by gummiboll** [comment] 2016-12-01 19:32
I was thinking something like:

```
DialContext: func(ctx context.Context, network, addr string) (net.Conn, error) {
        if p.rAddr.To4() != nil {
                return net.Dial("tcp4", addr)
        } else {
                return net.Dial("tcp6", addr)
        }
}
```
but will investigate however ```ResolveIPAddr``` prefers ipv4 or not first.

**Comment by mehrdadrad** [comment] 2016-12-01 19:49
type net.Addr doesn't have To4 as net.IP does. anyway, same solution. Thanks for investigating

**Comment by gummiboll** [comment] 2016-12-01 19:54
Ah, yeah - that's correct. So either change rAddr to net.IP or do a strings.Index. I kinda like the .To4()-solution better, looks cleaner but doesn't really matter. Both works. :)

If I read [this](https://golang.org/src/net/iprawsock.go#L66) correctly it seems like ```ResolveIPAddr``` does prefer ipv4 and from testing it seems to always return the ipv4-address but that kinda feels.. weird.

**Comment by mehrdadrad** [comment] 2016-12-01 20:40
@gummiboll check the myLG->ping how it works, if IPv6 available on the client and name server then it tries to use IPv6 but if IPv6 not available on the client or name server then it tries to use IPv4. it think this login is make sense. what do you think?

**Closed** 2016-12-02 06:07 UTC

**Comment by jungle-boogie** [comment] 2016-12-02 06:34
@gummiboll, @mehrdadrad, I think something is missing:

```
 -4                Force IPv4
 -6                Force IPv6
```

`hping -6 scanme.nmap.com` and even `hping -4 scanme.nmap.com` return the help for `hping`.

**Comment by mehrdadrad** [comment] 2016-12-02 07:05
@jungle-boogie 
    usage:
          hping url [options]
try hping scanme.nmap.com -6

**Comment by gummiboll** [comment] 2016-12-02 08:42
@mehrdadrad: Will fiddle and try to come up with a good solution and make a pr when done.

**Comment by jungle-boogie** [comment] 2016-12-02 16:21
thanks for implementing this!
